# Generated by Django 3.2 on 2022-07-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantCoordinates',
            new_name='AddressCoordinates',
        ),
    ]
