# Generated by Django 3.2 on 2022-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_rename_restaurantcoordinates_addresscoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscoordinates',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
