# Generated by Django 3.2 on 2022-08-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_alter_addresscoordinates_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscoordinates',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='addresscoordinates',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
