# Generated by Django 3.2 on 2022-06-27 20:09
import django.core.validators
from django.db import migrations, models


def calculate_order_item_price(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    db_alias = schema_editor.connection.alias
    order_items = OrderItem.objects.using(db_alias).all()
    print(order_items)
    for item in order_items:
        price = item.quantity * item.product.price
        item.price = price
        print(price)
        print(item.price)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена позиции', validators=[django.core.validators.MinValueValidator(0)], default=0),
        ),
        migrations.RunPython(calculate_order_item_price)
    ]
