# Generated by Django 3.2 on 2022-06-27 21:02

from django.db import migrations


def calculate_order_item_price(apps, schema_editor):
    OrderItem = apps.get_model("foodcartapp", "OrderItem")
    db_alias = schema_editor.connection.alias
    order_items = OrderItem.objects.using(db_alias).all()
    for item in order_items:
        price = item.quantity * item.product.price
        item.price = price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220627_2309'),
    ]

    operations = [
        migrations.RunPython(calculate_order_item_price)
    ]
