# Generated by Django 3.2 on 2022-06-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220628_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MN', 'Необработано'), ('REST', 'В ресторане'), ('CR', 'В доставке'), ('FN', 'Закрыт')], default='MN', max_length=4),
        ),
    ]
