# Generated by Django 3.2 on 2022-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
