# Generated by Django 3.2 on 2022-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20220713_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('EP', 'Электронный платеж'), ('CP', 'Наличными')], db_index=True, max_length=2),
        ),
    ]
