# Generated by Django 3.2.15 on 2022-10-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20220719_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu_items', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
